import cv2
import math
import os
import argparse 

cam = cv2.VideoCapture(0)

cam.set(3, 300)
cam.set(4, 400)
img_counter = 0
W = 300.
while True:
    ret, frame = cam.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    newimg = cv2.resize(gray, (200, 150))
    
    # cv2.imshow("Original", gray)
    # cv2.imshow("Editerino", newimg)
    y1 = math.floor(len(newimg)/2-112/2)
    y2 = math.floor(len(newimg)/2+112/2)
    x1 = math.floor(len(newimg[0])/2-92/2)
    x2 = math.floor(len(newimg[0])/2+92/2)
    crop = newimg[y1:y2, x1:x2]
    cv2.imshow("Croper", newimg[y1:y2, x1:x2])
    if not ret:
        break
    k = cv2.waitKey(1)

    if k % 256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break
    elif k % 256 == 32:
        # SPACE pressed
        img_name = "./imageOutput/{}.pgm".format(img_counter)
        cv2.imwrite("tempFile.pgm", crop)
        if not os.path.exists("./imageOutput"):
            os.mkdir("./imageOutput")
        with open("tempFile.pgm", 'rb') as f:
            newFile = open(img_name, 'wb')
            while True:
                b = f.read(1)
                if not b:
                    # eof
                    break
                if f.tell() < 3 or f.tell() > (len("# Generated by OpenCV 3.4.3")+3):
                    newFile.write(b)
            newFile.close()
            f.close()
        os.remove("tempFile.pgm")
        print("{} written!".format(img_name))
        # print(crop)
        img_counter+=1

cam.release()

cv2.destroyAllWindows()
